/*
 * MessageTreeTemplate.java
 *
 * Created on February 2, 2007, 2:58 PM
 */

package com.webreach.mirth.client.ui.editors;
import com.webreach.mirth.client.ui.HL7XMLTreePanel;
import com.webreach.mirth.client.ui.PlatformUI;
import com.webreach.mirth.client.ui.components.MirthComboBox;
import com.webreach.mirth.model.MessageObject;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import org.syntax.jedit.SyntaxDocument;
import org.syntax.jedit.tokenmarker.HL7TokenMarker;

/**
 *
 * @author  brendanh
 */
public class MessageTreeTemplate extends javax.swing.JPanel
{
    private SyntaxDocument HL7Doc;
    private HL7XMLTreePanel treePanel;
    private String currentMessage = "";
    
    /** Creates new form MessageTreeTemplate */
    public MessageTreeTemplate()
    {
        initComponents();
        try
        {
            resizePanes();
        }
        catch (Exception e)
        {
          
        }
        HL7Doc = new SyntaxDocument();
        HL7Doc.setTokenMarker(new HL7TokenMarker());
        pasteBox.setDocument(HL7Doc);
        pasteBox.setFont(EditorConstants.DEFAULT_FONT);
        
        //handles updating the tree
        pasteBox.getDocument().addDocumentListener(new DocumentListener(){

            private void updateText()
            {
                String message = pasteBox.getText();
                treePanel.setMessage(message);
                treePanel.revalidate();
                treePanel.repaint();
            }
            public void changedUpdate(DocumentEvent e) {
                updateText();
            }

            public void insertUpdate(DocumentEvent e) {
                updateText();
            }

            public void removeUpdate(DocumentEvent e) {
                updateText();
            }
        });
    }
    
    public void setTreePanel(String prefix, String suffix)
    {
        treePanel = new HL7XMLTreePanel(prefix, suffix);
        treeScrollPane.setViewportView(treePanel);
    }

    public String getMessage()
    {
        return pasteBox.getText().replace('\n', '\r');
    }
    
    public void setMessage(String msg)
    {
        if (msg != null)
            msg = msg.replace('\r', '\n');
        pasteBox.setText(msg);
    }
    
    public void resizePanes()
    {
        split.setDividerLocation((int)(PlatformUI.MIRTH_FRAME.currentContentPage.getHeight()/2 - PlatformUI.MIRTH_FRAME.currentContentPage.getHeight()/10));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        split = new javax.swing.JSplitPane();
        pasteBox = new com.webreach.mirth.client.ui.components.MirthSyntaxTextArea();
        treeScrollPane = new javax.swing.JScrollPane();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        split.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        split.setLeftComponent(pasteBox);

        split.setRightComponent(treeScrollPane);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, split, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, split, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.webreach.mirth.client.ui.components.MirthSyntaxTextArea pasteBox;
    private javax.swing.JSplitPane split;
    private javax.swing.JScrollPane treeScrollPane;
    // End of variables declaration//GEN-END:variables
    
}
