/*
 * MessageTreeTemplate.java
 *
 * Created on February 2, 2007, 2:58 PM
 */

package com.webreach.mirth.client.ui.editors;
import com.webreach.mirth.client.ui.TreePanel;
import com.webreach.mirth.client.ui.PlatformUI;
import com.webreach.mirth.client.ui.components.MirthComboBox;
import com.webreach.mirth.model.MessageObject;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JComboBox;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import org.syntax.jedit.SyntaxDocument;
import org.syntax.jedit.tokenmarker.HL7TokenMarker;

/**
 *
 * @author  brendanh
 */
public class MessageTreeTemplate extends javax.swing.JPanel
{
    public final String DEFAULT_TEXT = "Paste a sample message here.";
    
    private SyntaxDocument HL7Doc;
    private TreePanel treePanel;
    private String currentMessage = "";
    private JComboBox data;
    /** Creates new form MessageTreeTemplate */
    public MessageTreeTemplate()
    {
        
    }
    
    public MessageTreeTemplate(JComboBox dataType)
    {
        data = dataType;
        
        initComponents();
        try
        {
            resizePanes();
        }
        catch (Exception e)
        {
          
        }
        HL7Doc = new SyntaxDocument();
        HL7Doc.setTokenMarker(new HL7TokenMarker());
        pasteBox.setDocument(HL7Doc);
        pasteBox.setFont(EditorConstants.DEFAULT_FONT);
        
        //handles updating the tree
        pasteBox.getDocument().addDocumentListener(new DocumentListener()
        {
            public void changedUpdate(DocumentEvent e) {
                updateText();
            }

            public void insertUpdate(DocumentEvent e) {
                updateText();
            }

            public void removeUpdate(DocumentEvent e) {
                updateText();
            }
        });
    }
    
    private void updateText()
    {
        String message = pasteBox.getText();
        treePanel.setMessage((String)data.getSelectedItem(), message, DEFAULT_TEXT);
        treePanel.revalidate();
        treePanel.repaint();
    }
    
    public void setTreePanel(String prefix, String suffix)
    {
        treePanel = new TreePanel(prefix, suffix);
        treeScrollPane.setViewportView(treePanel);
    }

    public String getMessage()
    {
        return pasteBox.getText().replace('\n', '\r');
    }
    
    public void setMessage(String msg)
    {
        if (msg != null)
            msg = msg.replace('\r', '\n');
        pasteBox.setText(msg);
        pasteBoxFocusLost(null);
        updateText();
    }
    
    public void clearMessage()
    {
        treePanel.clearMessage();
        pasteBoxFocusLost(null);
        updateText();
    }
    
    public void resizePanes()
    {
        split.setDividerLocation((int)(PlatformUI.MIRTH_FRAME.currentContentPage.getHeight()/2 - PlatformUI.MIRTH_FRAME.currentContentPage.getHeight()/10));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        split = new javax.swing.JSplitPane();
        pasteBox = new com.webreach.mirth.client.ui.components.MirthSyntaxTextArea();
        treeScrollPane = new javax.swing.JScrollPane();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        split.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        pasteBox.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                pasteBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                pasteBoxFocusLost(evt);
            }
        });

        split.setLeftComponent(pasteBox);

        split.setRightComponent(treeScrollPane);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, split, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, split, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pasteBoxFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_pasteBoxFocusLost
    {//GEN-HEADEREND:event_pasteBoxFocusLost
        if(pasteBox.getText().length() == 0)
        {
            pasteBox.setText(DEFAULT_TEXT);
        }
    }//GEN-LAST:event_pasteBoxFocusLost

    private void pasteBoxFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_pasteBoxFocusGained
    {//GEN-HEADEREND:event_pasteBoxFocusGained
        if(pasteBox.getText().equals(DEFAULT_TEXT))
        {
            pasteBox.setText("");
        }
    }//GEN-LAST:event_pasteBoxFocusGained
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.webreach.mirth.client.ui.components.MirthSyntaxTextArea pasteBox;
    private javax.swing.JSplitPane split;
    private javax.swing.JScrollPane treeScrollPane;
    // End of variables declaration//GEN-END:variables
    
}
