/*
 * TabbedTemplatePanel.java
 *
 * Created on February 2, 2007, 1:50 PM
 */

package com.webreach.mirth.client.ui.editors;

import com.webreach.mirth.client.ui.FunctionListBuilder;
import com.webreach.mirth.client.ui.FunctionListHandler;
import com.webreach.mirth.client.ui.FunctionListItem;
import com.webreach.mirth.client.ui.HL7XMLTreePanel;
import com.webreach.mirth.client.ui.PlatformUI;
import com.webreach.mirth.client.ui.ReferenceTableHandler;
import com.webreach.mirth.client.ui.components.MirthSyntaxTextArea;
import com.webreach.mirth.client.ui.util.SQLParserUtil;
import com.webreach.mirth.model.Channel;
import com.webreach.mirth.model.Step;
import java.awt.BorderLayout;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import org.syntax.jedit.SyntaxDocument;
import org.syntax.jedit.tokenmarker.HL7TokenMarker;

/**
 *
 * @author  brendanh
 */
public class TabbedTemplatePanel extends javax.swing.JPanel
{
    private VariableReferenceTable globalVarTable, dbVarTable;
    private SyntaxDocument incomingHL7Doc, outgoingHL7Doc;
    private HL7XMLTreePanel incomingTreePanel, outgoingTreePanel;
    
    /** Creates new form TabbedTemplatePanel */
    public TabbedTemplatePanel()
    {
        initComponents();
        resizePanes();
        ArrayList<FunctionListItem> functionListItems = new FunctionListBuilder().getVariableListItems();
        variableReferenceTable = new VariableReferenceTable(functionListItems); 
        variableReferenceTable.setDragEnabled(true);  
        variableReferenceTable.setTransferHandler(new FunctionListHandler(functionListItems));  
        variableReferenceScrollPane.setViewportView(variableReferenceTable);
        incomingDataType.setModel(new javax.swing.DefaultComboBoxModel(PlatformUI.MIRTH_FRAME.protocols.values().toArray()));
        outgoingDataType.setModel(new javax.swing.DefaultComboBoxModel(PlatformUI.MIRTH_FRAME.protocols.values().toArray()));
        incoming.setTreePanel("msg", ".toString()");
        outgoing.setTreePanel("tmp", "");
    }
      
    public void resizePanes()
    {
        variableSplitPane.setDividerLocation((int)(PlatformUI.MIRTH_FRAME.currentContentPage.getHeight()/2 - PlatformUI.MIRTH_FRAME.currentContentPage.getHeight()/10));
        incoming.resizePanes();
        outgoing.resizePanes();
    }
    
    public void updateVariables(List<Step> steps)
    {
        variablePanel.updateVariables(steps);
    }
    
    public String getIncomingMessage()
    {
        return incoming.getMessage();
    }
    
    public void setIncomingMessage(String msg)
    {
        incoming.setMessage(msg);
    }
    
    public String getOutgoingMessage()
    {
        return outgoing.getMessage();
    }
    
    public void setOutgoingMessage(String msg)
    {
        outgoing.setMessage(msg);
    }
    
    public void setDefaultComponent()
    {
        tabPanel.setSelectedIndex(0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        tabPanel = new javax.swing.JTabbedPane();
        variableTab = new javax.swing.JPanel();
        variableSplitPane = new javax.swing.JSplitPane();
        variableReferenceScrollPane = new javax.swing.JScrollPane();
        variableReferenceTable = new com.webreach.mirth.client.ui.editors.VariableReferenceTable();
        variablePanel = new com.webreach.mirth.client.ui.editors.EditorVariableList();
        incomingTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        incomingDataType = new com.webreach.mirth.client.ui.components.MirthComboBox();
        incoming = new com.webreach.mirth.client.ui.editors.MessageTreeTemplate();
        outgoingTab = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        outgoingDataType = new com.webreach.mirth.client.ui.components.MirthComboBox();
        outgoing = new com.webreach.mirth.client.ui.editors.MessageTreeTemplate();

        variableSplitPane.setDividerLocation(84);
        variableSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        variableReferenceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        variableReferenceScrollPane.setViewportView(variableReferenceTable);

        variableSplitPane.setLeftComponent(variableReferenceScrollPane);

        variablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3), "Available Variables", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0)));
        variableSplitPane.setRightComponent(variablePanel);

        org.jdesktop.layout.GroupLayout variableTabLayout = new org.jdesktop.layout.GroupLayout(variableTab);
        variableTab.setLayout(variableTabLayout);
        variableTabLayout.setHorizontalGroup(
            variableTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, variableSplitPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );
        variableTabLayout.setVerticalGroup(
            variableTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(variableSplitPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        tabPanel.addTab("Reference", variableTab);

        incomingTab.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Type:");

        incomingDataType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        incomingDataType.setEnabled(false);

        org.jdesktop.layout.GroupLayout incomingTabLayout = new org.jdesktop.layout.GroupLayout(incomingTab);
        incomingTab.setLayout(incomingTabLayout);
        incomingTabLayout.setHorizontalGroup(
            incomingTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(incomingTabLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(incomingDataType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
            .add(incoming, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );
        incomingTabLayout.setVerticalGroup(
            incomingTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(incomingTabLayout.createSequentialGroup()
                .addContainerGap()
                .add(incomingTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(incomingDataType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(incoming, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
        );
        tabPanel.addTab("Incoming Data", incomingTab);

        outgoingTab.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data Type:");

        outgoingDataType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.layout.GroupLayout outgoingTabLayout = new org.jdesktop.layout.GroupLayout(outgoingTab);
        outgoingTab.setLayout(outgoingTabLayout);
        outgoingTabLayout.setHorizontalGroup(
            outgoingTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(outgoingTabLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(outgoingDataType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
            .add(outgoing, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );
        outgoingTabLayout.setVerticalGroup(
            outgoingTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(outgoingTabLayout.createSequentialGroup()
                .addContainerGap()
                .add(outgoingTabLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(outgoingDataType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(outgoing, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
        );
        tabPanel.addTab("Outgoing Data", outgoingTab);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.webreach.mirth.client.ui.editors.MessageTreeTemplate incoming;
    public com.webreach.mirth.client.ui.components.MirthComboBox incomingDataType;
    public javax.swing.JPanel incomingTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private com.webreach.mirth.client.ui.editors.MessageTreeTemplate outgoing;
    public com.webreach.mirth.client.ui.components.MirthComboBox outgoingDataType;
    public javax.swing.JPanel outgoingTab;
    public javax.swing.JTabbedPane tabPanel;
    private com.webreach.mirth.client.ui.editors.EditorVariableList variablePanel;
    private javax.swing.JScrollPane variableReferenceScrollPane;
    private com.webreach.mirth.client.ui.editors.VariableReferenceTable variableReferenceTable;
    private javax.swing.JSplitPane variableSplitPane;
    private javax.swing.JPanel variableTab;
    // End of variables declaration//GEN-END:variables
    
}
