/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is Mirth.
 *
 * The Initial Developer of the Original Code is
 * WebReach, Inc.
 * Portions created by the Initial Developer are Copyright (C) 2006
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *   Gerald Bortis <geraldb@webreachinc.com>
 *
 * ***** END LICENSE BLOCK ***** */

package com.webreach.mirth.client.ui;

import java.awt.Cursor;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import java.util.prefs.Preferences;

import javax.swing.JOptionPane;

import com.webreach.mirth.client.core.ClientException;
import com.webreach.mirth.client.ui.components.MirthFieldConstraints;
import com.webreach.mirth.client.ui.util.FileUtil;
import com.webreach.mirth.model.ServerConfiguration;
import com.webreach.mirth.model.converters.ObjectXMLSerializer;
import com.webreach.mirth.model.util.ImportConverter;

/**
 * The main configuration panel.
 */
public class SettingsPanel extends javax.swing.JPanel
{
    private static Preferences userPreferences;
    private Properties serverProperties;
    private Frame parent;

    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel()
    {
        this.parent = PlatformUI.MIRTH_FRAME;
        initComponents();

        this.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                showSettingsPopupMenu(evt);
            }

            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                showSettingsPopupMenu(evt);
            }
        });
        
        usageStatsMoreInfoLabel.setToolTipText(UIConstants.PRIVACY_TOOLTIP);
        usageStatsMoreInfoLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /** Shows the right click popup menu */
    private void showSettingsPopupMenu(java.awt.event.MouseEvent evt)
    {
        if (evt.isPopupTrigger())
        {
            parent.settingsPopupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        backupPanel = new javax.swing.JPanel();
        backupButton = new javax.swing.JButton();
        restoreButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lastBackup = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        smtpPassword = new com.webreach.mirth.client.ui.components.MirthPasswordField();
        passwordLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        smtpUsername = new com.webreach.mirth.client.ui.components.MirthTextField();
        requireAuthenticationYes = new com.webreach.mirth.client.ui.components.MirthRadioButton();
        requireAuthenticationNo = new com.webreach.mirth.client.ui.components.MirthRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        defaultFrom = new com.webreach.mirth.client.ui.components.MirthTextField();
        jLabel11 = new javax.swing.JLabel();
        smtpPort = new com.webreach.mirth.client.ui.components.MirthTextField();
        smtpHost = new com.webreach.mirth.client.ui.components.MirthTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        secureConnectionNone = new com.webreach.mirth.client.ui.components.MirthRadioButton();
        secureConnectionTLS = new com.webreach.mirth.client.ui.components.MirthRadioButton();
        secureConnectionSSL = new com.webreach.mirth.client.ui.components.MirthRadioButton();
        serverSettings = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        clearGlobalMapYes = new com.webreach.mirth.client.ui.components.MirthRadioButton();
        clearGlobalMapNo = new com.webreach.mirth.client.ui.components.MirthRadioButton();
        checkForUpdatesLabel = new javax.swing.JLabel();
        checkForUpdatesYes = new com.webreach.mirth.client.ui.components.MirthRadioButton();
        checkForUpdatesNo = new com.webreach.mirth.client.ui.components.MirthRadioButton();
        sendUsageStatsLabel = new javax.swing.JLabel();
        sendUsageStatsYes = new com.webreach.mirth.client.ui.components.MirthRadioButton();
        sendUsageStatsNo = new com.webreach.mirth.client.ui.components.MirthRadioButton();
        updateUrl = new com.webreach.mirth.client.ui.components.MirthTextField();
        updateUrlLabel = new javax.swing.JLabel();
        usageStatsMoreInfoLabel = new javax.swing.JLabel();
        clientSettings = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        intervalTime = new com.webreach.mirth.client.ui.components.MirthTextField();
        rowHighlightYes = new com.webreach.mirth.client.ui.components.MirthRadioButton();
        rowHighlightNo = new com.webreach.mirth.client.ui.components.MirthRadioButton();
        messageBrowserPageSizeField = new com.webreach.mirth.client.ui.components.MirthTextField();
        jLabel3 = new javax.swing.JLabel();
        asteriskLabel = new javax.swing.JLabel();
        asteriskLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        backupPanel.setBackground(new java.awt.Color(255, 255, 255));
        backupPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)), "Server Configuration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        backupButton.setText("Backup...");
        backupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupButtonActionPerformed(evt);
            }
        });

        restoreButton.setText("Restore...");
        restoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Last configuration backup:");

        lastBackup.setText("None");

        org.jdesktop.layout.GroupLayout backupPanelLayout = new org.jdesktop.layout.GroupLayout(backupPanel);
        backupPanel.setLayout(backupPanelLayout);
        backupPanelLayout.setHorizontalGroup(
            backupPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(backupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(backupPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(backupPanelLayout.createSequentialGroup()
                        .add(backupButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(restoreButton))
                    .add(backupPanelLayout.createSequentialGroup()
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lastBackup)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        backupPanelLayout.setVerticalGroup(
            backupPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(backupPanelLayout.createSequentialGroup()
                .add(backupPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(lastBackup))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(backupPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(restoreButton)
                    .add(backupButton))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)), "Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        passwordLabel.setText("Password:");

        usernameLabel.setText("Username:");

        requireAuthenticationYes.setBackground(new java.awt.Color(255, 255, 255));
        requireAuthenticationYes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        buttonGroup2.add(requireAuthenticationYes);
        requireAuthenticationYes.setSelected(true);
        requireAuthenticationYes.setText("Yes");
        requireAuthenticationYes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        requireAuthenticationYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requireAuthenticationYesActionPerformed(evt);
            }
        });

        requireAuthenticationNo.setBackground(new java.awt.Color(255, 255, 255));
        requireAuthenticationNo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        buttonGroup2.add(requireAuthenticationNo);
        requireAuthenticationNo.setText("No");
        requireAuthenticationNo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        requireAuthenticationNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requireAuthenticationNoActionPerformed(evt);
            }
        });

        jLabel12.setText("Require Authentication:");

        jLabel1.setText("Default from Address:");

        jLabel11.setText("SMTP Port:");

        jLabel10.setText("SMTP Host:");

        jLabel5.setText("Secure Connection:");

        secureConnectionNone.setBackground(new java.awt.Color(255, 255, 255));
        secureConnectionNone.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        buttonGroup6.add(secureConnectionNone);
        secureConnectionNone.setSelected(true);
        secureConnectionNone.setText("None");
        secureConnectionNone.setMargin(new java.awt.Insets(0, 0, 0, 0));
        secureConnectionNone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secureConnectionNoneActionPerformed(evt);
            }
        });

        secureConnectionTLS.setBackground(new java.awt.Color(255, 255, 255));
        secureConnectionTLS.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        buttonGroup6.add(secureConnectionTLS);
        secureConnectionTLS.setText("TLS");
        secureConnectionTLS.setMargin(new java.awt.Insets(0, 0, 0, 0));
        secureConnectionTLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secureConnectionTLSActionPerformed(evt);
            }
        });

        secureConnectionSSL.setBackground(new java.awt.Color(255, 255, 255));
        secureConnectionSSL.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        buttonGroup6.add(secureConnectionSSL);
        secureConnectionSSL.setText("SSL");
        secureConnectionSSL.setMargin(new java.awt.Insets(0, 0, 0, 0));
        secureConnectionSSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secureConnectionSSLActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel5)
                    .add(jLabel10)
                    .add(jLabel11)
                    .add(jLabel1)
                    .add(jLabel12)
                    .add(usernameLabel)
                    .add(passwordLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(defaultFrom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(smtpPassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .add(smtpUsername, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .add(jPanel1Layout.createSequentialGroup()
                                    .add(requireAuthenticationYes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(requireAuthenticationNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(smtpPort, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(smtpHost, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 117, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(122, 122, 122))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(secureConnectionNone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(secureConnectionTLS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(secureConnectionSSL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(130, 130, 130))))
        );

        jPanel1Layout.linkSize(new java.awt.Component[] {defaultFrom, smtpHost, smtpPassword, smtpUsername}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(smtpHost, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(smtpPort, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(defaultFrom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(secureConnectionNone, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(secureConnectionTLS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(secureConnectionSSL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(requireAuthenticationYes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(requireAuthenticationNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(smtpUsername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(usernameLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(passwordLabel)
                    .add(smtpPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        serverSettings.setBackground(new java.awt.Color(255, 255, 255));
        serverSettings.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)), "Server", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel2.setText("Clear global map on deploy:");

        clearGlobalMapYes.setBackground(new java.awt.Color(255, 255, 255));
        clearGlobalMapYes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        buttonGroup3.add(clearGlobalMapYes);
        clearGlobalMapYes.setSelected(true);
        clearGlobalMapYes.setText("Yes");
        clearGlobalMapYes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        clearGlobalMapYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearGlobalMapYesActionPerformed(evt);
            }
        });

        clearGlobalMapNo.setBackground(new java.awt.Color(255, 255, 255));
        clearGlobalMapNo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        buttonGroup3.add(clearGlobalMapNo);
        clearGlobalMapNo.setText("No");
        clearGlobalMapNo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        clearGlobalMapNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearGlobalMapNoActionPerformed(evt);
            }
        });

        checkForUpdatesLabel.setText("Check for updates:");

        checkForUpdatesYes.setBackground(new java.awt.Color(255, 255, 255));
        checkForUpdatesYes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        buttonGroup4.add(checkForUpdatesYes);
        checkForUpdatesYes.setSelected(true);
        checkForUpdatesYes.setText("Yes");
        checkForUpdatesYes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkForUpdatesYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkForUpdatesYesActionPerformed(evt);
            }
        });

        checkForUpdatesNo.setBackground(new java.awt.Color(255, 255, 255));
        checkForUpdatesNo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        buttonGroup4.add(checkForUpdatesNo);
        checkForUpdatesNo.setText("No");
        checkForUpdatesNo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        checkForUpdatesNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkForUpdatesNoActionPerformed(evt);
            }
        });

        sendUsageStatsLabel.setText("Provide usage statistics:");

        sendUsageStatsYes.setBackground(new java.awt.Color(255, 255, 255));
        sendUsageStatsYes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        buttonGroup5.add(sendUsageStatsYes);
        sendUsageStatsYes.setSelected(true);
        sendUsageStatsYes.setText("Yes");
        sendUsageStatsYes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        sendUsageStatsYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendUsageStatsYesActionPerformed(evt);
            }
        });

        sendUsageStatsNo.setBackground(new java.awt.Color(255, 255, 255));
        sendUsageStatsNo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        buttonGroup5.add(sendUsageStatsNo);
        sendUsageStatsNo.setText("No");
        sendUsageStatsNo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        sendUsageStatsNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendUsageStatsNoActionPerformed(evt);
            }
        });

        updateUrlLabel.setText("Update URL:");

        usageStatsMoreInfoLabel.setText("<html><font color=blue><u>More Info</u></font></html>");
        usageStatsMoreInfoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usageStatsMoreInfoLabelMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout serverSettingsLayout = new org.jdesktop.layout.GroupLayout(serverSettings);
        serverSettings.setLayout(serverSettingsLayout);
        serverSettingsLayout.setHorizontalGroup(
            serverSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(serverSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .add(serverSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(checkForUpdatesLabel)
                    .add(jLabel2)
                    .add(sendUsageStatsLabel)
                    .add(updateUrlLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(serverSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(serverSettingsLayout.createSequentialGroup()
                        .add(clearGlobalMapYes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(clearGlobalMapNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(serverSettingsLayout.createSequentialGroup()
                        .add(checkForUpdatesYes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(checkForUpdatesNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(serverSettingsLayout.createSequentialGroup()
                        .add(sendUsageStatsYes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sendUsageStatsNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(usageStatsMoreInfoLabel))
                    .add(updateUrl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        serverSettingsLayout.setVerticalGroup(
            serverSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(serverSettingsLayout.createSequentialGroup()
                .add(serverSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(clearGlobalMapYes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(clearGlobalMapNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(serverSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(checkForUpdatesLabel)
                    .add(checkForUpdatesYes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(checkForUpdatesNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(serverSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(sendUsageStatsLabel)
                    .add(sendUsageStatsYes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(sendUsageStatsNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(usageStatsMoreInfoLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(serverSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(updateUrl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(updateUrlLabel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clientSettings.setBackground(new java.awt.Color(255, 255, 255));
        clientSettings.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)), "Client", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel6.setText("Dashboard refresh interval (seconds):");

        jLabel7.setText("Alternate row highlighting in tables:");

        rowHighlightYes.setBackground(new java.awt.Color(255, 255, 255));
        rowHighlightYes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        buttonGroup1.add(rowHighlightYes);
        rowHighlightYes.setSelected(true);
        rowHighlightYes.setText("Yes");
        rowHighlightYes.setMargin(new java.awt.Insets(0, 0, 0, 0));

        rowHighlightNo.setBackground(new java.awt.Color(255, 255, 255));
        rowHighlightNo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        buttonGroup1.add(rowHighlightNo);
        rowHighlightNo.setText("No");
        rowHighlightNo.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel3.setText("Browser page size:");

        asteriskLabel.setForeground(new java.awt.Color(255, 0, 0));
        asteriskLabel.setText("*");

        asteriskLabel1.setForeground(new java.awt.Color(255, 0, 0));
        asteriskLabel1.setText("*");

        org.jdesktop.layout.GroupLayout clientSettingsLayout = new org.jdesktop.layout.GroupLayout(clientSettings);
        clientSettings.setLayout(clientSettingsLayout);
        clientSettingsLayout.setHorizontalGroup(
            clientSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(clientSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .add(clientSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel6)
                    .add(jLabel7)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(clientSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(clientSettingsLayout.createSequentialGroup()
                        .add(messageBrowserPageSizeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(asteriskLabel1))
                    .add(clientSettingsLayout.createSequentialGroup()
                        .add(rowHighlightYes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rowHighlightNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(clientSettingsLayout.createSequentialGroup()
                        .add(intervalTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(asteriskLabel)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        clientSettingsLayout.setVerticalGroup(
            clientSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(clientSettingsLayout.createSequentialGroup()
                .add(clientSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(intervalTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(asteriskLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(clientSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rowHighlightYes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rowHighlightNo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(clientSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(messageBrowserPageSizeField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3)
                    .add(asteriskLabel1))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(clientSettings, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(serverSettings, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(backupPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(clientSettings, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(serverSettings, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(backupPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void restoreButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_restoreButtonActionPerformed
    {//GEN-HEADEREND:event_restoreButtonActionPerformed
        if (parent.settingsTasks.getContentPane().getComponent(1).isVisible())
        {
            if (!parent.alertOkCancel(this, "Your new settings will first be saved.  Continue?"))
                return;
            saveSettings();
        }
        
    	File backupFile = parent.importFile("XML");
    	
    	if (backupFile != null)
    	{
    		String backupXML = null;
            try
            {
                backupXML = FileUtil.read(backupFile);
            }
            catch (IOException ex)
            {
                parent.alertError(this, "File could not be read.");
                return;
            }
            try
            {
                ObjectXMLSerializer serializer = new ObjectXMLSerializer();
                ServerConfiguration configuration = ImportConverter.convertServerConfiguration(backupXML);
                
                if (parent.alertOption(this, "Import configuration from " + configuration.getDate() + "?\nWARNING: This will overwrite all current channels, alerts, and server properties."))
                {
                    try
                    {
                        parent.mirthClient.setServerConfiguration(configuration);
                        parent.clearChannelCache();
                        loadSettings();
                        parent.alertInformation(this, "Your configuration was successfully restored.");
                    }
                    catch (ClientException e)
                    {
                        parent.alertException(this, e.getStackTrace(), e.getMessage());
                    }
                }
            }
            catch(Exception e)
            {
                parent.alertError(this, "Invalid server configuration file.");
            }
    	}
    }//GEN-LAST:event_restoreButtonActionPerformed

    private void backupButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backupButtonActionPerformed
    {//GEN-HEADEREND:event_backupButtonActionPerformed
        if (parent.settingsTasks.getContentPane().getComponent(1).isVisible())
        {
            int option = JOptionPane.showConfirmDialog(this, "Would you like to save the settings first?");

            if (option == JOptionPane.YES_OPTION)
                saveSettings();
            else if (option == JOptionPane.CANCEL_OPTION || option == JOptionPane.CLOSED_OPTION)
                return;
        }
        
        String backupDate = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
        
        ObjectXMLSerializer serializer = new ObjectXMLSerializer();
        ServerConfiguration configuration = null;
        try
        {
            configuration = parent.mirthClient.getServerConfiguration();
        }
        catch (ClientException e)
        {
            parent.alertException(this, e.getStackTrace(), e.getMessage());
            return;
        }
        
        configuration.setDate(backupDate);
        String backupXML = serializer.toXML(configuration);
        
        boolean fileWritten = parent.exportFile(backupXML, backupDate.substring(0,10) + " Mirth Backup.xml", "XML", "Server Configuration");
        if (fileWritten)
        {
        	userPreferences.put("lastBackup", backupDate);
            lastBackup.setText(backupDate);
        }
    }//GEN-LAST:event_backupButtonActionPerformed

    private void clearGlobalMapNoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clearGlobalMapNoActionPerformed
    {//GEN-HEADEREND:event_clearGlobalMapNoActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_clearGlobalMapNoActionPerformed

    private void clearGlobalMapYesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clearGlobalMapYesActionPerformed
    {//GEN-HEADEREND:event_clearGlobalMapYesActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_clearGlobalMapYesActionPerformed

private void checkForUpdatesYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkForUpdatesYesActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_checkForUpdatesYesActionPerformed

private void checkForUpdatesNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkForUpdatesNoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_checkForUpdatesNoActionPerformed

private void sendUsageStatsYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendUsageStatsYesActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_sendUsageStatsYesActionPerformed

private void sendUsageStatsNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendUsageStatsNoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_sendUsageStatsNoActionPerformed

private void usageStatsMoreInfoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usageStatsMoreInfoLabelMouseClicked
BareBonesBrowserLaunch.openURL(UIConstants.PRIVACY_URL);
}//GEN-LAST:event_usageStatsMoreInfoLabelMouseClicked

private void secureConnectionNoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secureConnectionNoneActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_secureConnectionNoneActionPerformed

private void secureConnectionTLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secureConnectionTLSActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_secureConnectionTLSActionPerformed

private void secureConnectionSSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secureConnectionSSLActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_secureConnectionSSLActionPerformed

    private void requireAuthenticationNoActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_requireAuthenticationNoActionPerformed
    {// GEN-HEADEREND:event_requireAuthenticationNoActionPerformed
        smtpUsername.setEnabled(false);
        smtpPassword.setEnabled(false);
        usernameLabel.setEnabled(false);
        passwordLabel.setEnabled(false);
    }// GEN-LAST:event_requireAuthenticationNoActionPerformed

    private void requireAuthenticationYesActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_requireAuthenticationYesActionPerformed
    {// GEN-HEADEREND:event_requireAuthenticationYesActionPerformed
        smtpUsername.setEnabled(true);
        smtpPassword.setEnabled(true);
        usernameLabel.setEnabled(true);
        passwordLabel.setEnabled(true);
    }// GEN-LAST:event_requireAuthenticationYesActionPerformed

    /** Loads the current settings into the Settings form */
    public void loadSettings()
    {
        intervalTime.setDocument(new MirthFieldConstraints(3, false, false, true));
        messageBrowserPageSizeField.setDocument(new MirthFieldConstraints(3, false, false, true));
        userPreferences = Preferences.userNodeForPackage(Mirth.class);
        int interval = userPreferences.getInt("intervalTime", 10);
        intervalTime.setText(interval + "");
        
        int messageBrowserPageSize = userPreferences.getInt("messageBrowserPageSize", 20);
        messageBrowserPageSizeField.setText(messageBrowserPageSize + "");

        if (userPreferences.getBoolean("highlightRows", true))
            rowHighlightYes.setSelected(true);
        else
            rowHighlightNo.setSelected(true);
        try
        {
            serverProperties = parent.mirthClient.getServerProperties();

            if (serverProperties.getProperty("smtp.host") != null)
                smtpHost.setText((String) serverProperties.getProperty("smtp.host"));
            else
                smtpHost.setText("");

            if (serverProperties.getProperty("smtp.port") != null)
                smtpPort.setText((String) serverProperties.getProperty("smtp.port"));
            else
                smtpPort.setText("");

            if (serverProperties.getProperty("smtp.from") != null)
                defaultFrom.setText((String) serverProperties.getProperty("smtp.from"));
            else
                defaultFrom.setText("");
            
            String smtpSecure = (String) serverProperties.getProperty("smtp.secure");
            if (smtpSecure != null && smtpSecure.equalsIgnoreCase("tls"))
                secureConnectionTLS.setSelected(true);
            else if (smtpSecure != null && smtpSecure.equalsIgnoreCase("ssl"))
                secureConnectionSSL.setSelected(true);
            else
                secureConnectionNone.setSelected(true);

            if (serverProperties.getProperty("smtp.auth") != null)
            {
                if (serverProperties.getProperty("smtp.auth").equals(UIConstants.YES_OPTION))
                {
                    requireAuthenticationYes.setSelected(true);
                    requireAuthenticationYesActionPerformed(null);
                }
                else
                {
                    requireAuthenticationNo.setSelected(true);
                    requireAuthenticationNoActionPerformed(null);
                }
            }
            else
            {
                requireAuthenticationNo.setSelected(true);
                requireAuthenticationNoActionPerformed(null);
            }
            
            if(serverProperties.getProperty("server.resetglobalvariables") != null)
            {
                if(serverProperties.getProperty("server.resetglobalvariables").equals(UIConstants.YES_OPTION))
                    clearGlobalMapYes.setSelected(true);
                else
                    clearGlobalMapNo.setSelected(true);
            }
            else
                clearGlobalMapYes.setSelected(true);
            
            if(serverProperties.getProperty("update.enabled") != null)
            {
                if(serverProperties.getProperty("update.enabled").equals(UIConstants.YES_OPTION))
                    checkForUpdatesYes.setSelected(true);
                else
                	checkForUpdatesNo.setSelected(true);
            }
            else
            	checkForUpdatesYes.setSelected(true);
            
            if(serverProperties.getProperty("stats.enabled") != null)
            {
                if(serverProperties.getProperty("stats.enabled").equals(UIConstants.YES_OPTION))
                    sendUsageStatsYes.setSelected(true);
                else
                	sendUsageStatsNo.setSelected(true);
            }
            else
            	sendUsageStatsYes.setSelected(true);
            
            if (serverProperties.getProperty("update.url") != null)
                updateUrl.setText((String) serverProperties.getProperty("update.url"));
            else
            	updateUrl.setText("");

            if (serverProperties.getProperty("smtp.username") != null)
                smtpUsername.setText((String) serverProperties.getProperty("smtp.username"));
            else
                smtpUsername.setText("");

            if (serverProperties.getProperty("smtp.password") != null)
                smtpPassword.setText((String) serverProperties.getProperty("smtp.password"));
            else
                smtpPassword.setText("");
            
            lastBackup.setText(userPreferences.get("lastBackup", "None"));
        }
        catch (ClientException e)
        {
            parent.alertException(this, e.getStackTrace(), e.getMessage());
        }
    }

    /** Saves the current settings from the settings form */
    public void saveSettings()
    {
        if (intervalTime.getText().length() == 0)
        {
            parent.alertWarning(this, "Please enter a valid interval time.");
            return;
        }
        if (messageBrowserPageSizeField.getText().length() == 0)
        {
            parent.alertWarning(this, "Please enter a valid message browser page size.");
            return;
        }

        int interval = Integer.parseInt(intervalTime.getText());
        int messageBrowserPageSize = Integer.parseInt(messageBrowserPageSizeField.getText());
        
        if (interval <= 0)
            parent.alertWarning(this, "Please enter an interval time that is larger than 0.");
        else if (messageBrowserPageSize <= 0)
            parent.alertWarning(this, "Please enter an message browser page size larger than 0.");
        else
        {
            userPreferences.putInt("intervalTime", interval);
            userPreferences.putInt("messageBrowserPageSize", messageBrowserPageSize);
            userPreferences.putBoolean("highlightRows", rowHighlightYes.isSelected());
            
            if(clearGlobalMapNo.isSelected())
                serverProperties.put("server.resetglobalvariables", UIConstants.NO_OPTION);
            else
                serverProperties.put("server.resetglobalvariables", UIConstants.YES_OPTION);
            
            if(checkForUpdatesNo.isSelected())
                serverProperties.put("update.enabled", UIConstants.NO_OPTION);
            else
                serverProperties.put("update.enabled", UIConstants.YES_OPTION);
            
            if(sendUsageStatsNo.isSelected())
                serverProperties.put("stats.enabled", UIConstants.NO_OPTION);
            else
                serverProperties.put("stats.enabled", UIConstants.YES_OPTION);
            
            serverProperties.put("update.url", updateUrl.getText());
            
            serverProperties.put("smtp.host", smtpHost.getText());
            serverProperties.put("smtp.port", smtpPort.getText());
            serverProperties.put("smtp.from", defaultFrom.getText());
            
            if (secureConnectionTLS.isSelected())
            	serverProperties.put("smtp.secure", "tls");
            else if (secureConnectionSSL.isSelected())
            	serverProperties.put("smtp.secure", "ssl");
            else
            	serverProperties.put("smtp.secure", "none");

            if (requireAuthenticationYes.isSelected())
            {
                serverProperties.put("smtp.auth", UIConstants.YES_OPTION);
                serverProperties.put("smtp.username", smtpUsername.getText());
                serverProperties.put("smtp.password", new String(smtpPassword.getPassword()));
            }
            else
            {
                serverProperties.put("smtp.auth", UIConstants.NO_OPTION);
                serverProperties.put("smtp.username", "");
                serverProperties.put("smtp.password", "");
            }
            
            try
            {
                parent.mirthClient.setServerProperties(serverProperties);
            }
            catch (ClientException e)
            {
                parent.alertException(this, e.getStackTrace(), e.getMessage());
            }
            parent.settingsTasks.getContentPane().getComponent(1).setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asteriskLabel;
    private javax.swing.JLabel asteriskLabel1;
    private javax.swing.JButton backupButton;
    private javax.swing.JPanel backupPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel checkForUpdatesLabel;
    private com.webreach.mirth.client.ui.components.MirthRadioButton checkForUpdatesNo;
    private com.webreach.mirth.client.ui.components.MirthRadioButton checkForUpdatesYes;
    private com.webreach.mirth.client.ui.components.MirthRadioButton clearGlobalMapNo;
    private com.webreach.mirth.client.ui.components.MirthRadioButton clearGlobalMapYes;
    private javax.swing.JPanel clientSettings;
    private com.webreach.mirth.client.ui.components.MirthTextField defaultFrom;
    private com.webreach.mirth.client.ui.components.MirthTextField intervalTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastBackup;
    private com.webreach.mirth.client.ui.components.MirthTextField messageBrowserPageSizeField;
    private javax.swing.JLabel passwordLabel;
    private com.webreach.mirth.client.ui.components.MirthRadioButton requireAuthenticationNo;
    private com.webreach.mirth.client.ui.components.MirthRadioButton requireAuthenticationYes;
    private javax.swing.JButton restoreButton;
    private com.webreach.mirth.client.ui.components.MirthRadioButton rowHighlightNo;
    private com.webreach.mirth.client.ui.components.MirthRadioButton rowHighlightYes;
    private com.webreach.mirth.client.ui.components.MirthRadioButton secureConnectionNone;
    private com.webreach.mirth.client.ui.components.MirthRadioButton secureConnectionSSL;
    private com.webreach.mirth.client.ui.components.MirthRadioButton secureConnectionTLS;
    private javax.swing.JLabel sendUsageStatsLabel;
    private com.webreach.mirth.client.ui.components.MirthRadioButton sendUsageStatsNo;
    private com.webreach.mirth.client.ui.components.MirthRadioButton sendUsageStatsYes;
    private javax.swing.JPanel serverSettings;
    private com.webreach.mirth.client.ui.components.MirthTextField smtpHost;
    private com.webreach.mirth.client.ui.components.MirthPasswordField smtpPassword;
    private com.webreach.mirth.client.ui.components.MirthTextField smtpPort;
    private com.webreach.mirth.client.ui.components.MirthTextField smtpUsername;
    private com.webreach.mirth.client.ui.components.MirthTextField updateUrl;
    private javax.swing.JLabel updateUrlLabel;
    private javax.swing.JLabel usageStatsMoreInfoLabel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

}
