DROP TABLE TEMPLATE

ALTER TABLE CHANNEL_STATISTICS DROP CONSTRAINT CHANNEL_STATS_ID_FK

ALTER TABLE CHANNEL_ALERT DROP CONSTRAINT ALERT_ID_CA_FK

ALTER TABLE ALERT_EMAIL DROP CONSTRAINT ALERT_ID_AE_FK

ALTER TABLE MESSAGE DROP CONSTRAINT CHANNEL_ID_FK

RENAME TABLE CHANNEL_STATISTICS TO "__CHANNEL_STATISTICS"

RENAME TABLE ATTACHMENT TO "__ATTACHMENT"

RENAME TABLE MESSAGE TO "__MESSAGE"

RENAME TABLE CHANNEL_ALERT TO "__CHANNEL_ALERT"

RENAME TABLE ALERT_EMAIL TO "__ALERT_EMAIL"

RENAME TABLE ALERT TO "__ALERT"

RENAME TABLE CHANNEL TO "__CHANNEL"

RENAME TABLE CODE_TEMPLATE TO "__CODE_TEMPLATE"

CREATE TABLE CHANNEL (
	ID VARCHAR(36) NOT NULL PRIMARY KEY,
	NAME VARCHAR(40) NOT NULL,
	REVISION INTEGER,
	CHANNEL CLOB
)

CREATE TABLE ALERT (
	ID VARCHAR(36) NOT NULL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL UNIQUE,
	ALERT CLOB NOT NULL
)

CREATE TABLE CODE_TEMPLATE (
	ID VARCHAR(255) NOT NULL PRIMARY KEY,
	CODE_TEMPLATE CLOB
)

UPDATE SCRIPT SET GROUP_ID = 'Global' WHERE GROUP_ID = 'GLOBAL'

CREATE DERBY AGGREGATE GROUP_CONCAT FOR VARCHAR(1024) EXTERNAL NAME 'com.mirth.connect.server.util.DerbyGroupConcat';
