ALTER TABLE CONFIGURATION ALTER COLUMN VALUE NULL

INSERT INTO CONFIGURATION (CATEGORY, NAME, VALUE) VALUES ('core', 'server.maxqueuesize', '0')

DROP TABLE EVENT

CREATE TABLE EVENT
	(ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
	DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	NAME CLOB NOT NULL,
	EVENT_LEVEL VARCHAR(40) NOT NULL,
	OUTCOME VARCHAR(40),
	ATTRIBUTES CLOB,
	USER_ID INTEGER NOT NULL,
	IP_ADDRESS VARCHAR(40))

ALTER TABLE SCRIPT ALTER GROUP_ID SET DATA TYPE VARCHAR(40)

ALTER TABLE SCRIPT ALTER ID SET DATA TYPE VARCHAR(40)

ALTER TABLE CODE_TEMPLATE ALTER COLUMN TOOLTIP NULL
