DROP TABLE TRANSPORT

ALTER TABLE CHANNEL ADD COLUMN DEPLOY_SCRIPT CLOB DEFAULT NULL

ALTER TABLE CHANNEL ADD COLUMN SHUTDOWN_SCRIPT CLOB DEFAULT NULL

ALTER TABLE CHANNEL ADD COLUMN POSTPROCESSING_SCRIPT CLOB DEFAULT NULL

CREATE TABLE SCHEMA_INFO
		(VERSION VARCHAR(40))
