ALTER TABLE PERSON ALTER COLUMN PASSWORD SET DATA TYPE VARCHAR(256)

ALTER TABLE PERSON ALTER COLUMN PASSWORD NOT NULL

UPDATE PERSON SET PASSWORD = 'SALT_' || SALT || PASSWORD

ALTER TABLE PERSON DROP COLUMN SALT