ALTER TABLE PERSON ALTER COLUMN PASSWORD SET DATA TYPE VARCHAR(256)

ALTER TABLE PERSON ALTER COLUMN PASSWORD NOT NULL

UPDATE PERSON SET PASSWORD = 'SALT_' || SALT || PASSWORD

ALTER TABLE PERSON DROP COLUMN SALT

CREATE TABLE PERSON_PASSWORD
	(PERSON_ID INTEGER NOT NULL,
	PASSWORD VARCHAR(256) NOT NULL,
	PASSWORD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PERSON_ID_PP_FK FOREIGN KEY(PERSON_ID) REFERENCES PERSON(ID) ON DELETE CASCADE)

INSERT INTO PERSON_PASSWORD (PERSON_ID, PASSWORD) SELECT ID, PASSWORD FROM PERSON

ALTER TABLE PERSON DROP COLUMN PASSWORD

ALTER TABLE PERSON ADD COLUMN GRACE_PERIOD_START TIMESTAMP DEFAULT NULL