ALTER TABLE PERSON ALTER PASSWORD SET DATA TYPE VARCHAR(256)

CONSTRAINT PERSON_PASSWORD_CONSTRAINT CHECK (PASSWORD IS NOT NULL)

UPDATE PERSON SET PASSWORD = 'SALT_' || SALT || PASSWORD

ALTER TABLE PERSON DROP COLUMN SALT