ALTER TABLE CONFIGURATION MODIFY VALUE LONGTEXT NULL

INSERT INTO CONFIGURATION (CATEGORY, NAME, VALUE) VALUES ('core', 'server.maxqueuesize', '0')

DROP TABLE EVENT

CREATE TABLE EVENT
	(ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	NAME LONGTEXT NOT NULL,
	EVENT_LEVEL VARCHAR(40) NOT NULL,
	OUTCOME VARCHAR(40),
	ATTRIBUTES LONGTEXT,
	USER_ID INTEGER NOT NULL,
	IP_ADDRESS VARCHAR(40)) ENGINE=InnoDB

ALTER TABLE SCRIPT MODIFY COLUMN GROUP_ID VARCHAR(40)

ALTER TABLE SCRIPT MODIFY COLUMN ID VARCHAR(40)

ALTER TABLE CODE_TEMPLATE MODIFY TOOLTIP VARCHAR(255) NULL
