DROP TABLE TEMPLATE

RENAME TABLE CHANNEL_ALERT TO OLD_CHANNEL_ALERT

RENAME TABLE ALERT_EMAIL TO OLD_ALERT_EMAIL

RENAME TABLE ALERT TO OLD_ALERT

RENAME TABLE MESSAGE TO OLD_MESSAGE

RENAME TABLE ATTACHMENT TO OLD_ATTACHMENT

RENAME TABLE CHANNEL_STATISTICS TO OLD_CHANNEL_STATISTICS

RENAME TABLE CHANNEL TO OLD_CHANNEL

RENAME TABLE CODE_TEMPLATE TO OLD_CODE_TEMPLATE

CREATE TABLE CHANNEL (
	ID CHAR(36) NOT NULL PRIMARY KEY,
	NAME VARCHAR(40) NOT NULL,
	REVISION INTEGER,
	CHANNEL LONGTEXT
) ENGINE=InnoDB

CREATE TABLE ALERT (
	ID VARCHAR(36) NOT NULL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL UNIQUE,
	ALERT LONGTEXT NOT NULL
) ENGINE=InnoDB

CREATE TABLE CODE_TEMPLATE (
	ID VARCHAR(255) NOT NULL PRIMARY KEY,
	CODE_TEMPLATE LONGTEXT
) ENGINE=InnoDB

UPDATE SCRIPT SET GROUP_ID = 'Global' WHERE GROUP_ID = 'GLOBAL'

DELETE FROM CONFIGURATION WHERE CATEGORY = 'core' AND NAME = 'server.maxqueuesize'

INSERT INTO CONFIGURATION (CATEGORY, NAME, VALUE) VALUES ('core', 'server.queuebuffersize', '1000')