DROP TABLE TEMPLATE

RENAME TABLE CHANNEL_STATISTICS TO __CHANNEL_STATISTICS

RENAME TABLE ATTACHMENT TO __ATTACHMENT

RENAME TABLE MESSAGE TO __MESSAGE

RENAME TABLE ALERT TO __ALERT

RENAME TABLE CHANNEL_ALERT TO __CHANNEL_ALERT

RENAME TABLE ALERT_EMAIL TO __ALERT_EMAIL

RENAME TABLE CHANNEL TO __CHANNEL

RENAME TABLE CODE_TEMPLATE TO __CODE_TEMPLATE

CREATE TABLE CHANNEL (
	ID CHAR(36) NOT NULL PRIMARY KEY,
	NAME VARCHAR(40) NOT NULL,
	REVISION INTEGER,
	CHANNEL LONGTEXT
) ENGINE=InnoDB

CREATE TABLE ALERT (
	ID VARCHAR(36) NOT NULL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL UNIQUE,
	ALERT LONGTEXT NOT NULL
) ENGINE=InnoDB

CREATE TABLE CODE_TEMPLATE (
	ID VARCHAR(255) NOT NULL PRIMARY KEY,
	CODE_TEMPLATE LONGTEXT
) ENGINE=InnoDB