CREATE TABLE DEBUGGER_USAGE (
    ID INTEGER  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SERVER_ID CHARACTER VARYING(50) NOT NULL,
    DUPP_COUNT INTEGER,
    ATTACH_BATCH_COUNT INTEGER,
    SOURCE_CONNECTOR_COUNT INTEGER,
    SOURCE_FILTER_TRANS_COUNT INTEGER,
    DESTINATION_FILTER_TRANS_COUNT INTEGER,
    DESTINATION_CONNECTOR_COUNT INTEGER,
    RESPONSE_COUNT INTEGER,
    INVOCATION_COUNT INTEGER
) ENGINE=InnoDB

ALTER TABLE PERSON ADD COLUMN ROLE VARCHAR(40)

ALTER TABLE PERSON ADD COLUMN COUNTRY VARCHAR(40)

ALTER TABLE PERSON ADD COLUMN STATETERRITORY VARCHAR(40)

ALTER TABLE PERSON ADD COLUMN USERCONSENT BOOLEAN NOT NULL DEFAULT false
