DROP TABLE TRANSPORT

ALTER TABLE EVENT MODIFY COLUMN EVENT LONGTEXT DEFAULT NULL

ALTER TABLE EVENT MODIFY COLUMN DESCRIPTION LONGTEXT DEFAULT NULL

ALTER TABLE EVENT MODIFY COLUMN ATTRIBUTES LONGTEXT DEFAULT NULL

ALTER TABLE CHANNEL MODIFY COLUMN SOURCE_CONNECTOR LONGTEXT DEFAULT NULL

ALTER TABLE CHANNEL MODIFY COLUMN DESCRIPTION LONGTEXT DEFAULT NULL

ALTER TABLE CHANNEL MODIFY COLUMN PROPERTIES LONGTEXT DEFAULT NULL

ALTER TABLE CHANNEL MODIFY COLUMN DESTINATION_CONNECTORS LONGTEXT DEFAULT NULL

ALTER TABLE CHANNEL MODIFY COLUMN DESCRIPTION LONGTEXT DEFAULT NULL

ALTER TABLE CHANNEL MODIFY COLUMN PREPROCESSING_SCRIPT LONGTEXT DEFAULT NULL

ALTER TABLE MESSAGE MODIFY COLUMN RAW_DATA LONGTEXT DEFAULT NULL

ALTER TABLE MESSAGE MODIFY COLUMN TRANSFORMED_DATA LONGTEXT DEFAULT NULL

ALTER TABLE MESSAGE MODIFY COLUMN ENCODED_DATA LONGTEXT DEFAULT NULL

ALTER TABLE MESSAGE MODIFY COLUMN CONNECTOR_MAP LONGTEXT DEFAULT NULL

ALTER TABLE MESSAGE MODIFY COLUMN CHANNEL_MAP LONGTEXT DEFAULT NULL

ALTER TABLE MESSAGE MODIFY COLUMN RESPONSE_MAP LONGTEXT DEFAULT NULL

ALTER TABLE MESSAGE MODIFY COLUMN ERRORS LONGTEXT DEFAULT NULL

ALTER TABLE SCRIPT MODIFY COLUMN SCRIPT LONGTEXT DEFAULT NULL

ALTER TABLE TEMPLATE MODIFY COLUMN TEMPLATE LONGTEXT DEFAULT NULL

ALTER TABLE ALERT MODIFY COLUMN EXPRESSION LONGTEXT DEFAULT NULL

ALTER TABLE ALERT MODIFY COLUMN TEMPLATE LONGTEXT DEFAULT NULL

ALTER TABLE CONFIGURATION MODIFY COLUMN DATA LONGTEXT DEFAULT NULL

ALTER TABLE CHANNEL ADD COLUMN DEPLOY_SCRIPT LONGTEXT DEFAULT NULL

ALTER TABLE CHANNEL ADD COLUMN SHUTDOWN_SCRIPT LONGTEXT DEFAULT NULL

ALTER TABLE CHANNEL ADD COLUMN POSTPROCESSING_SCRIPT LONGTEXT DEFAULT NULL

CREATE TABLE SCHEMA_INFO
		(VERSION VARCHAR(40))
