DROP TABLE TEMPLATE

DROP SEQUENCE MESSAGE_SEQUENCE

ALTER TABLE CHANNEL_STATISTICS RENAME TO __CHANNEL_STATISTICS

ALTER TABLE ATTACHMENT RENAME TO __ATTACHMENT

ALTER TABLE MESSAGE RENAME TO __MESSAGE

ALTER TABLE ALERT RENAME TO __ALERT

ALTER TABLE CHANNEL_ALERT RENAME TO __CHANNEL_ALERT

ALTER TABLE ALERT_EMAIL RENAME TO __ALERT_EMAIL

ALTER TABLE CHANNEL RENAME TO __CHANNEL

ALTER TABLE CODE_TEMPLATE RENAME TO __CODE_TEMPLATE

CREATE TABLE CHANNEL (
	ID CHAR(36) NOT NULL PRIMARY KEY,
	NAME VARCHAR(40) NOT NULL,
	REVISION NUMBER(10),
	CHANNEL CLOB
)

CREATE TABLE CHANNEL_TAGS (
	CHANNEL_ID CHAR(36) NOT NULL,
	TAG VARCHAR(255) NOT NULL,
	CONSTRAINT CHANNEL_TAGS_PKEY PRIMARY KEY (channel_id, tag)
)

CREATE TABLE ALERT (
	ID VARCHAR(36) NOT NULL PRIMARY KEY,
	NAME VARCHAR(256) NOT NULL UNIQUE,
	ALERT CLOB NOT NULL
)

CREATE TABLE CODE_TEMPLATE (
	ID VARCHAR(255) NOT NULL PRIMARY KEY,
	CODE_TEMPLATE CLOB
)