CREATE TABLE PERSON_PREFERENCE
	(PERSON_ID NUMBER(10) NOT NULL REFERENCES PERSON(ID) ON DELETE CASCADE,
	NAME VARCHAR(255) NOT NULL,
	VALUE CLOB)

CREATE INDEX PERSON_PREFERENCE_INDEX1 ON PERSON_PREFERENCE(PERSON_ID)
	
ALTER TABLE PERSON ADD (INDUSTRY VARCHAR(255) DEFAULT NULL)

INSERT INTO PERSON_PREFERENCE (PERSON_ID, NAME, VALUE) SELECT ID, 'firstlogin', 'false' FROM PERSON

DELETE FROM CONFIGURATION WHERE CATEGORY = 'core' AND NAME = 'firstlogin'

DELETE FROM CONFIGURATION WHERE CATEGORY = 'core' AND NAME = 'update.enabled'

DELETE FROM CONFIGURATION WHERE CATEGORY = 'core' AND NAME = 'update.url'

UPDATE SCRIPT SET ID = 'Undeploy' WHERE GROUP_ID = 'Global' AND ID = 'Shutdown'