CREATE TABLE PERSON_PREFERENCES
	(PERSON_ID NUMBER(10) NOT NULL REFERENCES PERSON(ID) ON DELETE CASCADE,
	NAME VARCHAR(255) NOT NULL,
	VALUE CLOB)

CREATE INDEX PERSON_PREFERENCES_INDEX1 ON PERSON_PREFERENCES(PERSON_ID)
	
ALTER TABLE PERSON ADD (INDUSTRY VARCHAR(255) DEFAULT NULL)

UPDATE SCRIPT SET ID = 'Undeploy' WHERE GROUP_ID = 'Global' AND ID = 'Shutdown'