ALTER TABLE PERSON MODIFY PASSWORD VARCHAR(256) NOT NULL

UPDATE PERSON SET PASSWORD = 'SALT_' || SALT || PASSWORD

ALTER TABLE PERSON DROP COLUMN SALT

CREATE TABLE PERSON_PASSWORD
	(PERSON_ID INTEGER NOT NULL REFERENCES PERSON(ID) ON DELETE CASCADE,
	PASSWORD VARCHAR(256) NOT NULL,
	PASSWORD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP)

INSERT INTO PERSON_PASSWORD (PERSON_ID, PASSWORD) SELECT ID, PASSWORD FROM PERSON

ALTER TABLE PERSON DROP COLUMN PASSWORD

ALTER TABLE PERSON ADD (GRACE_PERIOD_START TIMESTAMP DEFAULT NULL)

INSERT INTO CONFIGURATION (CATEGORY, NAME, VALUE) VALUES ('core', 'smtp.timeout', '5000')

INSERT INTO CONFIGURATION (CATEGORY, NAME, VALUE) VALUES ('core', 'encryption.key', (SELECT DATA FROM ENCRYPTION_KEY))

DROP TABLE ENCRYPTION_KEY