DROP TABLE TRANSPORT

ALTER TABLE CHANNEL 
ADD 
   (
      DEPLOY_SCRIPT 	CLOB DEFAULT NULL,
      SHUTDOWN_SCRIPT   CLOB DEFAULT NULL,
	  POSTPROCESSING_SCRIPT   CLOB DEFAULT NULL
   )

CREATE TABLE SCHEMA_INFO
		(VERSION VARCHAR(40))
