DROP TABLE TEMPLATE;

DROP SEQUENCE MESSAGE_SEQUENCE CASCADE;

-- TODO: decide if we want to migrate stats
-- TODO: decide if we want to drop any of these tables
ALTER TABLE CHANNEL_STATISTICS RENAME TO __CHANNEL_STATISTICS;
ALTER TABLE ATTACHMENT RENAME TO __ATTACHMENT;
ALTER TABLE MESSAGE RENAME TO __MESSAGE;
ALTER TABLE ALERT RENAME TO __ALERT;
ALTER TABLE CHANNEL_ALERT RENAME TO __CHANNEL_ALERT;
ALTER TABLE ALERT_EMAIL RENAME TO __ALERT_EMAIL;

ALTER TABLE CHANNEL ADD COLUMN NEXT_METADATA_ID INTEGER;
UPDATE CHANNEL SET NEXT_METADATA_ID = 1;
ALTER TABLE CHANNEL ALTER COLUMN NEXT_METADATA_ID SET NOT NULL;

CREATE TABLE CHANNEL_TAGS (
	CHANNEL_ID CHAR(36) NOT NULL,
	TAG VARCHAR(255) NOT NULL,
	CONSTRAINT CHANNEL_TAGS_PKEY PRIMARY KEY (channel_id, tag)
);

-- TODO fix error, postgres fails to create new alert table because it says it already exists
--CREATE TABLE ALERT
	(ID CHAR(36) NOT NULL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL UNIQUE,
	ALERT TEXT NOT NULL);
