DROP TABLE TEMPLATE

DROP SEQUENCE MESSAGE_SEQUENCE CASCADE

ALTER TABLE CHANNEL_STATISTICS RENAME TO __CHANNEL_STATISTICS

ALTER TABLE ATTACHMENT RENAME TO __ATTACHMENT

ALTER TABLE MESSAGE RENAME TO __MESSAGE

ALTER TABLE ALERT RENAME TO __ALERT

ALTER TABLE CHANNEL_ALERT RENAME TO __CHANNEL_ALERT

ALTER TABLE ALERT_EMAIL RENAME TO __ALERT_EMAIL

ALTER TABLE CHANNEL RENAME TO __CHANNEL

ALTER TABLE CODE_TEMPLATE RENAME TO __CODE_TEMPLATE

CREATE TABLE CHANNEL (
	ID CHAR(36) NOT NULL PRIMARY KEY,
	NAME VARCHAR(40) NOT NULL,
	REVISION INTEGER,
	CHANNEL TEXT
)

CREATE TABLE ALERT (
	ID CHAR(36) NOT NULL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL UNIQUE,
	ALERT TEXT NOT NULL
)

CREATE TABLE CODE_TEMPLATE (
	ID VARCHAR(255) NOT NULL PRIMARY KEY,
	CODE_TEMPLATE TEXT
)	