DROP TABLE IF EXISTS TRANSPORT

ALTER TABLE CHANNEL ADD COLUMN DEPLOY_SCRIPT TEXT DEFAULT NULL

ALTER TABLE CHANNEL ADD COLUMN SHUTDOWN_SCRIPT TEXT DEFAULT NULL

ALTER TABLE CHANNEL ADD COLUMN POSTPROCESSING_SCRIPT TEXT DEFAULT NULL

CREATE TABLE IF NOT EXISTS SCHEMA_INFO
		(VERSION VARCHAR(40))
