ALTER TABLE CHANNEL ADD COLUMN LAST_MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP

ALTER TABLE PERSON ADD COLUMN LAST_LOGIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP

ALTER TABLE MESSAGE ADD COLUMN ATTACHMENT BOOLEAN DEFAULT FALSE

CREATE TABLE ATTACHMENT
    (ID VARCHAR(255) NOT NULL PRIMARY KEY,
     MESSAGE_ID VARCHAR(255) NOT NULL,
     ATTACHMENT_DATA BYTEA,
     ATTACHMENT_SIZE INTEGER,
     ATTACHMENT_TYPE VARCHAR(40))
