
CREATE TABLE DEBUGGER_USAGE
(
    ID SERIAL NOT NULL,
    SERVER_ID CHARACTER VARYING(50) NOT NULL,
    DUPP_COUNT INTEGER,
    ATTACH_BATCH_COUNT INTEGER,
    SOURCE_CONNECTOR_COUNT INTEGER,
    SOURCE_FILTER_TRANS_COUNT INTEGER,
    DESTINATION_FILTER_TRANS_COUNT INTEGER,
    DESTINATION_CONNECTOR_COUNT INTEGER,
    RESPONSE_COUNT INTEGER,
    INVOCATION_COUNT INTEGER,
    LAST_SENT TIMESTAMP,
    CONSTRAINT DEBUGGER_USAGE_PKEY PRIMARY KEY (ID)
)
