CREATE TABLE PERSON_PREFERENCES
	(PERSON_ID INTEGER NOT NULL REFERENCES PERSON(ID) ON DELETE CASCADE,
	NAME VARCHAR(255) NOT NULL,
	VALUE TEXT)
	
CREATE INDEX PERSON_PREFERENCES_INDEX1 ON PERSON_PREFERENCES USING BTREE (PERSON_ID)

ALTER TABLE PERSON ADD COLUMN INDUSTRY VARCHAR(255) DEFAULT NULL