CREATE TABLE PERSON_PREFERENCE (
	PERSON_ID INTEGER NOT NULL,
	NAME NVARCHAR(255) NOT NULL,
	VALUE NVARCHAR(MAX)
)

CREATE INDEX PERSON_PREFERENCE_INDEX1 ON PERSON_PREFERENCE(PERSON_ID)

ALTER TABLE PERSON ADD INDUSTRY VARCHAR(255) DEFAULT NULL

INSERT INTO PERSON_PREFERENCE (NAME, VALUE, PERSON_ID) SELECT 'firstlogin', 'false', ID FROM PERSON

DELETE FROM CONFIGURATION WHERE CATEGORY = 'core' AND NAME = 'firstlogin'

DELETE FROM CONFIGURATION WHERE CATEGORY = 'core' AND NAME = 'update.enabled'

DELETE FROM CONFIGURATION WHERE CATEGORY = 'core' AND NAME = 'update.url'

UPDATE SCRIPT SET ID = 'Undeploy' WHERE GROUP_ID = 'Global' AND ID = 'Shutdown'