DROP TABLE TEMPLATE

SP_RENAME CHANNEL_ALERT, OLD_CHANNEL_ALERT

SP_RENAME ALERT_EMAIL, OLD_ALERT_EMAIL

SP_RENAME ALERT, OLD_ALERT

SP_RENAME MESSAGE, OLD_MESSAGE

SP_RENAME ATTACHMENT, OLD_ATTACHMENT

SP_RENAME CHANNEL_STATISTICS, OLD_CHANNEL_STATISTICS

SP_RENAME CHANNEL, OLD_CHANNEL

SP_RENAME CODE_TEMPLATE, OLD_CODE_TEMPLATE

CREATE TABLE CHANNEL (
	ID NVARCHAR(36) NOT NULL PRIMARY KEY,
	NAME NVARCHAR(40) NOT NULL,
	REVISION INTEGER,
	CHANNEL NVARCHAR(MAX)
)

CREATE TABLE ALERT (
	ID CHAR(36) NOT NULL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL UNIQUE,
	ALERT TEXT NOT NULL
)

CREATE TABLE CODE_TEMPLATE (
	ID NVARCHAR(255) NOT NULL PRIMARY KEY,
	CODE_TEMPLATE NVARCHAR(MAX)
)

UPDATE SCRIPT SET GROUP_ID = 'Global' WHERE GROUP_ID = 'GLOBAL'

DELETE FROM CONFIGURATION WHERE CATEGORY = 'core' AND NAME = 'server.maxqueuesize'

INSERT INTO CONFIGURATION (CATEGORY, NAME, VALUE) VALUES ('core', 'server.queuebuffersize', '1000')