CREATE TABLE DEBUGGER_USAGE
    (ID INTEGER IDENTITY (1, 1) NOT NULL PRIMARY KEY,
    SERVER_ID NVARCHAR(50) NOT NULL,
    DUPP_COUNT INTEGER,
    ATTACH_BATCH_COUNT INTEGER,
    SOURCE_CONNECTOR_COUNT INTEGER,
    SOURCE_FILTER_TRANS_COUNT INTEGER,
    DESTINATION_FILTER_TRANS_COUNT INTEGER,
    DESTINATION_CONNECTOR_COUNT INTEGER,
    RESPONSE_COUNT INTEGER,
    INVOCATION_COUNT INTEGER)

ALTER TABLE PERSON ADD ROLE NVARCHAR(40)

ALTER TABLE PERSON ADD COUNTRY NVARCHAR(40)

ALTER TABLE PERSON ADD STATETERRITORY NVARCHAR(40)

ALTER TABLE PERSON ADD USERCONSENT BIT NOT NULL DEFAULT 0
