ALTER TABLE PERSON ADD FIRSTNAME VARCHAR(40) DEFAULT NULL

ALTER TABLE PERSON ADD LASTNAME VARCHAR(40) DEFAULT NULL

ALTER TABLE PERSON ADD ORGANIZATION VARCHAR(255) DEFAULT NULL

ALTER TABLE PERSON DROP COLUMN FULLNAME

ALTER TABLE CHANNEL_STATISTICS ADD ALERTED INTEGER DEFAULT 0

CREATE TABLE PREFERENCES (PERSON_ID INTEGER NOT NULL, NAME VARCHAR(255) NOT NULL, VALUE VARCHAR(255))

ALTER TABLE PREFERENCES ADD CONSTRAINT PERSON_ID_PR_FK FOREIGN KEY (PERSON_ID) REFERENCES PERSON (ID)
