DROP TABLE TEMPLATE

ALTER TABLE CHANNEL_STATISTICS RENAME TO _CHANNEL_STATISTICS

ALTER TABLE ATTACHMENT RENAME TO _ATTACHMENT

ALTER TABLE MESSAGE RENAME TO _MESSAGE

ALTER TABLE ALERT RENAME TO _ALERT

ALTER TABLE CHANNEL_ALERT RENAME TO _CHANNEL_ALERT

ALTER TABLE ALERT_EMAIL RENAME TO _ALERT_EMAIL

ALTER TABLE CHANNEL RENAME TO __CHANNEL

CREATE TABLE CHANNEL (
	ID NVARCHAR(36) NOT NULL PRIMARY KEY,
	NAME NVARCHAR(40) NOT NULL,
	REVISION INTEGER,
	CHANNEL NVARCHAR(MAX)
)

CREATE TABLE CHANNEL_TAGS (
	CHANNEL_ID NVARCHAR(36) NOT NULL,
	TAG NVARCHAR(255) NOT NULL,
	PRIMARY KEY(CHANNEL_ID, TAG)
)

CREATE TABLE ALERT (
	ID CHAR(36) NOT NULL PRIMARY KEY,
	NAME VARCHAR(256) NOT NULL UNIQUE,
	ALERT TEXT NOT NULL
)