DROP TABLE CONFIGURATION;

CREATE TABLE CONFIGURATION
	(CATEGORY VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	VALUE CLOB NOT NULL);	
	
DROP TABLE PREFERENCES;

DROP TABLE SCRIPT;

CREATE TABLE SCRIPT
	(GROUP_ID VARCHAR(255) NOT NULL,
	ID VARCHAR(255) NOT NULL,
	SCRIPT CLOB);
	
ALTER TABLE SCRIPT ADD PRIMARY KEY (GROUP_ID, ID);	

DROP TABLE TEMPLATE;

CREATE TABLE TEMPLATE
	(GROUP_ID VARCHAR(255) NOT NULL,
	ID VARCHAR(255) NOT NULL,
	TEMPLATE CLOB);

ALTER TABLE TEMPLATE ADD PRIMARY KEY (GROUP_ID, ID);