ALTER TABLE PERSON ADD COLUMN FIRSTNAME VARCHAR(40) DEFAULT NULL

ALTER TABLE PERSON ADD COLUMN LASTNAME VARCHAR(40) DEFAULT NULL

ALTER TABLE PERSON ADD COLUMN ORGANIZATION VARCHAR(255) DEFAULT NULL

ALTER TABLE PERSON DROP COLUMN FULLNAME

ALTER TABLE CHANNEL_STATISTICS ADD COLUMN ALERTED INTEGER DEFAULT 0
