DROP TABLE CONFIGURATION;

CREATE TABLE CONFIGURATION
	(CATEGORY VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	VALUE LONGTEXT NOT NULL) ENGINE=InnoDB;
	
DROP TABLE PREFERENCES;

DROP TABLE IF EXISTS SCRIPT;

CREATE TABLE SCRIPT
	(GROUP_ID VARCHAR(255) NOT NULL,
	ID VARCHAR(255) NOT NULL,
	SCRIPT LONGTEXT,
	PRIMARY KEY(GROUP_ID, ID)) ENGINE=InnoDB;

DROP TABLE IF EXISTS CODE_TEMPLATE;

CREATE TABLE CODE_TEMPLATE
	(GROUP_ID VARCHAR(255) NOT NULL,
	ID VARCHAR(255) NOT NULL,
	NAME VARCHAR(40) NOT NULL,
	CODE_SCOPE VARCHAR(40) NOT NULL,
	CODE_TYPE VARCHAR(40) NOT NULL,
	TOOLTIP VARCHAR(255) NOT NULL,
	CODE LONGTEXT,
	PRIMARY KEY(GROUP_ID, ID)) ENGINE=InnoDB;