ALTER TABLE CHANNEL 
ADD 
   (
		LAST_MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
   }
   
ALTER TABLE PERSON LAST_LOGIN
ADD 
   (
		LAST_LOGIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP
   }
   
ALTER TABLE MESSAGE 
ADD 
   (
      ATTACHMENT 	SMALLINT DEFAULT NULL
   )
   
CREATE TABLE ATTACHMENT
    (ID VARCHAR(255) NOT NULL PRIMARY KEY,
     MESSAGE_ID VARCHAR(255) NOT NULL,
     DATA BLOB,
     SIZE INTEGER,
     TYPE VARCHAR(40))