ALTER TABLE CHANNEL 
ADD 
   (
		LAST_MODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
   )
   
ALTER TABLE PERSON
ADD 
   (
		LAST_LOGIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP
   )
   
ALTER TABLE MESSAGE 
ADD 
   (
      ATTACHMENT 	SMALLINT DEFAULT 0
   )
   
CREATE TABLE ATTACHMENT
    (ID VARCHAR(255) NOT NULL PRIMARY KEY,
     MESSAGE_ID VARCHAR(255) NOT NULL,
     ATTACHMENT_DATA BLOB,
     ATTACHMENT_SIZE INTEGER,
     ATTACHMENT_TYPE VARCHAR(40))