DROP TABLE CONFIGURATION;

CREATE TABLE CONFIGURATION
	(CATEGORY VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	VALUE CLOB NOT NULL);
	
DROP TABLE PREFERENCES;

DROP TABLE SCRIPT;

CREATE TABLE SCRIPT
	(GROUP_ID VARCHAR(255) NOT NULL,
	ID VARCHAR(255) NOT NULL,
	SCRIPT CLOB,
	PRIMARY KEY(GROUP_ID, ID);
	
DROP TABLE CODE_TEMPLATE;

CREATE TABLE CODE_TEMPLATE
	(GROUP_ID VARCHAR(255) NOT NULL,
	ID VARCHAR(255) NOT NULL,
	NAME VARCHAR(40) NOT NULL,
	CODE_SCOPE VARCHAR(40) NOT NULL,
	CODE_TYPE VARCHAR(40) NOT NULL,
	TOOLTIP VARCHAR(255) NOT NULL,
	CODE CLOB,
	PRIMARY KEY(GROUP_ID, ID));	