DROP TABLE CONFIGURATION;

CREATE TABLE CONFIGURATION
	(CATEGORY VARCHAR(255) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	VALUE CLOB NOT NULL);
	
DROP TABLE PREFERENCES;

ALTER TABLE SCRIPT ADD (GROUP_ID VARCHAR(255);

UPDATE SCRIPT SET GROUP = 'GLOBAL' WHERE ID = 'Deploy' OR ID = 'Shutdown' OR ID = 'Preprocessor' OR ID = 'Postprocessor';

ALTER TABLE SCRIPT DROP PRIMARY KEY;

ALTER TABLE SCRIPT ADD PRIMARY KEY (GROUP_ID, ID);
	
DELETE FROM TEMPLATE;

ALTER TABLE TEMPLATE ADD (GROUP_ID VARCHAR(255) NOT NULL);

ALTER TABLE TEMPLATE ADD PRIMARY KEY (GROUP_ID, ID);