ALTER TABLE MESSAGE ADD COLUMN ATTACHMENT BOOLEAN DEFAULT NULL

CREATE TABLE ATTACHMENT
    (ID VARCHAR(255) NOT NULL PRIMARY KEY,
     MESSAGE_ID VARCHAR(255) NOT NULL,
     DATA BYTEA,
     SIZE INTEGER,
     TYPE VARCHAR(40))
