ALTER TABLE MESSAGE ADD ATTACHMENT SMALLINT DEFAULT NULL

CREATE TABLE ATTACHMENT
    (ID VARCHAR(255) NOT NULL PRIMARY KEY,
     MESSAGE_ID VARCHAR(255) NOT NULL,
     DATA IMAGE,
     SIZE INTEGER,
     TYPE VARCHAR(40))
