package com.mirth.connect.connectors.jdbc;

import java.util.Map;

import com.mirth.connect.donkey.model.message.ConnectorMessage;
import com.mirth.connect.donkey.server.DeployException;
import com.mirth.connect.donkey.server.UndeployException;

public interface DatabaseReceiverDelegate {
    public void deploy() throws DeployException;

    public void undeploy() throws UndeployException;

    /**
     * Execute the poll query and return an object representing the results
     * 
     * @return Either a ResultSet or List&lt;Map&lt;String, Object&gt;&gt;
     */
    public Object poll() throws DatabaseReceiverException, InterruptedException;

    /**
     * Run the post-process sql/script after polling is complete (if post-process is set to 'once'
     * in the UI) and perform any required clean up operations.
     */
    public void afterPoll() throws DatabaseReceiverException, InterruptedException;

    /**
     * Run the post-process sql/script after each message is processed (if post-process is set to
     * 'each' in the UI)
     * 
     * @param resultMap
     *            The result that was retrieved by the select query/script
     * @param mergedConnectorMessage
     *            The merged ConnectorMessage generated by the channel after processing (null if the
     *            channel is responding immediately and not waiting for the message to finish
     *            processing)
     */
    public void runPostProcess(Map<String, Object> resultMap, ConnectorMessage mergedConnectorMessage) throws DatabaseReceiverException, InterruptedException;
}
