/*
 * ChannelSetup.java
 *
 * Created on April 28, 2006, 11:05 AM
 */

package com.webreach.mirth.client;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import com.webreach.mirth.client.ChannelInfo;

/**
 *
 * @author  brendanh
 */
public class ChannelSetup extends javax.swing.JPanel
{
    ArrayList<ChannelInfo> channelViews;
    ChannelInfo currentChannel;
    int index;
    /**
     * Creates new form ChannelSetup
     */
    Frame parent;
    
    public ChannelSetup(JFrame parent)
    {
        initComponents();
        this.parent = (Frame)parent;
        index = -1;
        if (jRadioButton1.isSelected())
        {
            jTextPane1.setBackground(new java.awt.Color(236,233,216));
            jTextPane1.setEnabled(false);
        }
        if (jRadioButton3.isSelected())
        {
            jTextPane2.setBackground(new java.awt.Color(236,233,216));
            jTextPane2.setEnabled(false);
        }
        channelView.setMaximumSize(new Dimension(450, 3000));
    }
    
    public void editChannel(int index)
    {
        this.index = index;
        currentChannel = parent.channels.get(index);
        loadChannelInfo();
    }
    
    public void removeChannel(int channelIndex) 
    {                                             
        parent.channels.remove(channelIndex);
        parent.channelListPage.makeChannelTable();
    }                                            

    public void addChannel() 
    {   
        index = -1;
        currentChannel = new ChannelInfo();
        loadChannelInfo();
    }
    
    private void loadChannelInfo()
    {
        summaryChannelName.setText(currentChannel.channelName);
    }
    
    public boolean saveChanges()
    {
        if (summaryChannelName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(parent, "Channel name cannot be empty.");
                    return false;
        }
        if (!currentChannel.channelName.equals(summaryChannelName.getText()))
        {
            for (int i = 0; i < parent.channels.size(); i++)
            {
                if (parent.channels.get(i).channelName.equals(summaryChannelName.getText()))
                {
                    JOptionPane.showMessageDialog(parent, "Channel name already exists.");
                    return false;
                }
            }
        }
        
        currentChannel.channelName = summaryChannelName.getText();
        
        if(index == -1)
        {
            index = parent.channels.size();
            parent.channels.add(currentChannel);
        }
        else
            parent.channels.set(index,currentChannel);
        
        parent.channelListPage.makeChannelTable();
        return true;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        filterButtonGroup = new javax.swing.ButtonGroup();
        validationButtonGroup = new javax.swing.ButtonGroup();
        channelView = new javax.swing.JTabbedPane();
        summary = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        summaryChannelName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        source = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addSourceButton = new javax.swing.JButton();
        editSourceButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        filter = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        validation = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jComboBox3 = new javax.swing.JComboBox();
        jRadioButton4 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        destination = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        summary.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Channel Name:");

        jLabel9.setText("Channel Description:");

        summaryChannelName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                summaryChannelNameKeyTyped(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Channel Description");
        jScrollPane2.setViewportView(jTextArea1);

        org.jdesktop.layout.GroupLayout summaryLayout = new org.jdesktop.layout.GroupLayout(summary);
        summary.setLayout(summaryLayout);
        summaryLayout.setHorizontalGroup(
            summaryLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(summaryLayout.createSequentialGroup()
                .addContainerGap()
                .add(summaryLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel8)
                    .add(jLabel9))
                .add(7, 7, 7)
                .add(summaryLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 287, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(summaryChannelName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        summaryLayout.setVerticalGroup(
            summaryLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(summaryLayout.createSequentialGroup()
                .addContainerGap()
                .add(summaryLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(summaryChannelName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(22, 22, 22)
                .add(summaryLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        channelView.addTab("Summary", summary);

        source.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TCP/IP", "Database", "Email" }));

        jLabel2.setText("Property 1:");

        jLabel3.setText("Property 2:");

        addSourceButton.setText("New");

        editSourceButton.setText("Edit");

        jLabel5.setText("Source:");

        org.jdesktop.layout.GroupLayout sourceLayout = new org.jdesktop.layout.GroupLayout(source);
        source.setLayout(sourceLayout);
        sourceLayout.setHorizontalGroup(
            sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(sourceLayout.createSequentialGroup()
                .add(28, 28, 28)
                .add(sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jLabel2)
                    .add(jLabel5))
                .add(38, 38, 38)
                .add(sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField2)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField1)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15)
                .add(addSourceButton)
                .add(15, 15, 15)
                .add(editSourceButton)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        sourceLayout.linkSize(new java.awt.Component[] {addSourceButton, editSourceButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        sourceLayout.setVerticalGroup(
            sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(sourceLayout.createSequentialGroup()
                .add(19, 19, 19)
                .add(sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(sourceLayout.createSequentialGroup()
                        .add(9, 9, 9)
                        .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(sourceLayout.createSequentialGroup()
                        .add(1, 1, 1)
                        .add(sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jComboBox1)
                            .add(addSourceButton)
                            .add(editSourceButton))))
                .add(24, 24, 24)
                .add(sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE, false)
                    .add(sourceLayout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabel2))
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(27, 27, 27)
                .add(sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE, false)
                    .add(sourceLayout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabel3))
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(303, 303, 303))
        );
        channelView.addTab("Source", source);

        filter.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Filter 1", "Filter 2", "Filter 3" }));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        filterButtonGroup.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Standard Filter:");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        filterButtonGroup.add(jRadioButton2);
        jRadioButton2.setText("Custom Filter:");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTextPane1);

        org.jdesktop.layout.GroupLayout filterLayout = new org.jdesktop.layout.GroupLayout(filter);
        filter.setLayout(filterLayout);
        filterLayout.setHorizontalGroup(
            filterLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(filterLayout.createSequentialGroup()
                .add(filterLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(filterLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(filterLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(filterLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jRadioButton1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jRadioButton2)))
                    .add(filterLayout.createSequentialGroup()
                        .add(27, 27, 27)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 419, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        filterLayout.setVerticalGroup(
            filterLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(filterLayout.createSequentialGroup()
                .add(37, 37, 37)
                .add(filterLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton1)
                    .add(jComboBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(28, 28, 28)
                .add(jRadioButton2)
                .add(15, 15, 15)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 280, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        channelView.addTab("Filter", filter);

        validation.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        validationButtonGroup.add(jRadioButton3);
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Standard Validator:");
        jRadioButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Validator 1", "Validator 2", "Validator 3" }));

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        validationButtonGroup.add(jRadioButton4);
        jRadioButton4.setText("Custom Validator:");
        jRadioButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jTextPane2);

        org.jdesktop.layout.GroupLayout validationLayout = new org.jdesktop.layout.GroupLayout(validation);
        validation.setLayout(validationLayout);
        validationLayout.setHorizontalGroup(
            validationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(validationLayout.createSequentialGroup()
                .add(validationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(validationLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jRadioButton3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jComboBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(validationLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jRadioButton4))
                    .add(validationLayout.createSequentialGroup()
                        .add(27, 27, 27)
                        .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 417, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        validationLayout.setVerticalGroup(
            validationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(validationLayout.createSequentialGroup()
                .add(37, 37, 37)
                .add(validationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jComboBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jRadioButton3))
                .add(28, 28, 28)
                .add(jRadioButton4)
                .add(15, 15, 15)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 280, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        channelView.addTab("Validation", validation);

        destination.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Destination 1", "Destination 2", "Destination 3", "Destination 4" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TCP/IP", "Database", "Email" }));

        jButton1.setText("New");

        jButton3.setText("Edit");

        jLabel1.setText("Property 1:");

        jLabel4.setText("Property 2:");

        jLabel6.setText("Source");

        org.jdesktop.layout.GroupLayout destinationLayout = new org.jdesktop.layout.GroupLayout(destination);
        destination.setLayout(destinationLayout);
        destinationLayout.setHorizontalGroup(
            destinationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(destinationLayout.createSequentialGroup()
                .add(33, 33, 33)
                .add(destinationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jComboBox5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(destinationLayout.createSequentialGroup()
                        .add(destinationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel1)
                            .add(jLabel4)
                            .add(jLabel6))
                        .add(39, 39, 39)
                        .add(destinationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField4)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField3)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jComboBox6, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(16, 16, 16)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 14, Short.MAX_VALUE)
                        .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(177, 177, 177))
        );
        destinationLayout.setVerticalGroup(
            destinationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(destinationLayout.createSequentialGroup()
                .add(26, 26, 26)
                .add(jComboBox5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(destinationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE, false)
                    .add(destinationLayout.createSequentialGroup()
                        .add(1, 1, 1)
                        .add(jComboBox6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jButton1)
                    .add(jButton3)
                    .add(destinationLayout.createSequentialGroup()
                        .add(9, 9, 9)
                        .add(jLabel6)))
                .add(24, 24, 24)
                .add(destinationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE, false)
                    .add(destinationLayout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabel1))
                    .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(24, 24, 24)
                .add(destinationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE, false)
                    .add(destinationLayout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLabel4))
                    .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(262, 262, 262))
        );
        channelView.addTab("Destinations", destination);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(channelView, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(channelView, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void summaryChannelNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_summaryChannelNameKeyTyped
// TODO add your handling code here:
        parent.channelEditTasks.getContentPane().getComponent(0).setVisible(true);
    }//GEN-LAST:event_summaryChannelNameKeyTyped

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
// TODO add your handling code here:
        jTextPane1.setBackground(new java.awt.Color(255,255,255));
        jTextPane1.setEnabled(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
// TODO add your handling code here:
        jTextPane1.setBackground(new java.awt.Color(236,233,216));
        jTextPane1.setEnabled(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
// TODO add your handling code here:
        jTextPane2.setBackground(new java.awt.Color(236,233,216));
        jTextPane2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
// TODO add your handling code here:
        jTextPane2.setBackground(new java.awt.Color(255,255,255));
        jTextPane2.setEnabled(true);
    }//GEN-LAST:event_jRadioButton4ActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSourceButton;
    private javax.swing.JTabbedPane channelView;
    private javax.swing.JPanel destination;
    private javax.swing.JButton editSourceButton;
    private javax.swing.JPanel filter;
    private javax.swing.ButtonGroup filterButtonGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JPanel source;
    private javax.swing.JPanel summary;
    private javax.swing.JTextField summaryChannelName;
    private javax.swing.JPanel validation;
    private javax.swing.ButtonGroup validationButtonGroup;
    // End of variables declaration//GEN-END:variables
    
}
